import Head from 'next/head'
import Register from './components/Register'

export default function Home() {
  return (
    <>
      <Head>
        <title >Locumator frontend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='main' aria-label='Main Content'>
        <section className='section split-background'>
          <div className='section-left'>
            <div className='section-inner'>
              <div className='section-content'>
                <h2 className='section-title'>The on-demand, all inclusive, healthcare management ecosystem</h2>
              </div>
            </div>
          </div>
          <div className=' section-right'>
            <div className='section-inner'>
              <div className='section-form'>
                <h3 className='section-subtitle'>Create an Account</h3>
                <Register />
              </div>
            </div>
          </div>

        </section>
      </main>
    </>
  )
}
